type: AgentRigid
effectors:
  - type: Rigid
    params:
      init_pos: (0.5, 0.5, 0.5)
      init_euler: (0.0, 0.0, 0.0)
      action_dim: 3
      action_scale_p: (1.0, 1.0, 1.0)
      action_scale_v: (1.0, 1.0, 1.0)
    mesh:
      file: plate.obj
      scale: (0.3, 0.2, 0.3)
      euler: (0.0, 90.0, 0.0)
      material: PLATE
      softness: 100.0
    boundary:
      type: cube
      lower: (0.45, 0.25, 0.05)
      upper: (0.95, 0.95, 0.95)